export const monitors = [
  {
    id: "mon_01",
    name: "Auth Service Health",
    project: "Customer Portal",
    method: "GET",
    url: "https://api.acme.com/v2/auth/health",
    status: "operational" as const,
    uptime: 99.98,
    avgLatency: 138,
    p95Latency: 312,
    failedChecks: 0,
    lastResponseCode: 200,
    expectedStatus: 200,
    region: "us-east-1",
    interval: "30s",
    lastChecked: "8s ago",
  },
  {
    id: "mon_02",
    name: "Payments API",
    project: "Payments Infrastructure",
    method: "POST",
    url: "https://api.acme.com/v2/charge",
    status: "operational" as const,
    uptime: 99.94,
    avgLatency: 192,
    p95Latency: 412,
    failedChecks: 1,
    lastResponseCode: 200,
    expectedStatus: 200,
    region: "us-east-1",
    interval: "30s",
    lastChecked: "12s ago",
  },
  {
    id: "mon_03",
    name: "Notifications Worker",
    project: "Notification Services",
    method: "POST",
    url: "https://workers.acme.com/notify",
    status: "down" as const,
    uptime: 96.21,
    avgLatency: 0,
    p95Latency: 0,
    failedChecks: 18,
    lastResponseCode: 503,
    expectedStatus: 200,
    region: "eu-west-1",
    interval: "30s",
    lastChecked: "4s ago",
  },
  {
    id: "mon_04",
    name: "Customer Search",
    project: "Customer Portal",
    method: "GET",
    url: "https://api.acme.com/v2/customers/search",
    status: "degraded" as const,
    uptime: 99.42,
    avgLatency: 612,
    p95Latency: 1280,
    failedChecks: 4,
    lastResponseCode: 200,
    expectedStatus: 200,
    region: "ap-southeast-1",
    interval: "60s",
    lastChecked: "22s ago",
  },
  {
    id: "mon_05",
    name: "Public Gateway",
    project: "Core Banking APIs",
    method: "GET",
    url: "https://gateway.acme.com/health",
    status: "operational" as const,
    uptime: 99.99,
    avgLatency: 64,
    p95Latency: 142,
    failedChecks: 0,
    lastResponseCode: 200,
    expectedStatus: 200,
    region: "us-west-2",
    interval: "30s",
    lastChecked: "5s ago",
  },
  {
    id: "mon_06",
    name: "Claims Submission API",
    project: "Claims Platform",
    method: "POST",
    url: "https://api.acme.com/v1/claims",
    status: "operational" as const,
    uptime: 99.91,
    avgLatency: 248,
    p95Latency: 522,
    failedChecks: 0,
    lastResponseCode: 200,
    expectedStatus: 200,
    region: "us-east-1",
    interval: "60s",
    lastChecked: "30s ago",
  },
  {
    id: "mon_07",
    name: "Image CDN",
    project: "Customer Portal",
    method: "GET",
    url: "https://cdn.acme.com/healthz",
    status: "operational" as const,
    uptime: 99.97,
    avgLatency: 28,
    p95Latency: 64,
    failedChecks: 0,
    lastResponseCode: 200,
    expectedStatus: 200,
    region: "global",
    interval: "30s",
    lastChecked: "9s ago",
  },
  {
    id: "mon_08",
    name: "Webhooks Dispatcher",
    project: "Notification Services",
    method: "POST",
    url: "https://hooks.acme.com/dispatch",
    status: "degraded" as const,
    uptime: 98.76,
    avgLatency: 488,
    p95Latency: 1120,
    failedChecks: 9,
    lastResponseCode: 200,
    expectedStatus: 200,
    region: "eu-west-1",
    interval: "30s",
    lastChecked: "11s ago",
  },
]

export const liveChecks = Array.from({ length: 14 }).map((_, i) => {
  const m = monitors[i % monitors.length]
  const failed = m.status === "down" && i < 4
  const status = failed ? 503 : m.status === "degraded" && i % 3 === 0 ? 200 : 200
  return {
    time: `14:32:${String(60 - i * 3).padStart(2, "0")}`,
    monitor: m.name,
    region: m.region,
    status,
    latency: failed ? 0 : m.avgLatency + (i % 5) * 7,
  }
})

export const projects = [
  {
    id: "proj_01",
    name: "Core Banking APIs",
    description: "Account, ledger, and transaction services. Mission-critical with strict SLAs.",
    monitors: 8,
    uptime: 99.96,
    incidents: 0,
    status: "operational" as const,
    owner: "Platform Team",
    lastCheck: "12s ago",
  },
  {
    id: "proj_02",
    name: "Claims Platform",
    description: "Claims intake, processing, and underwriting APIs.",
    monitors: 6,
    uptime: 99.91,
    incidents: 1,
    status: "operational" as const,
    owner: "Claims Team",
    lastCheck: "30s ago",
  },
  {
    id: "proj_03",
    name: "Customer Portal",
    description: "Public-facing portal for end users including auth and search.",
    monitors: 5,
    uptime: 99.82,
    incidents: 1,
    status: "degraded" as const,
    owner: "Frontend Team",
    lastCheck: "22s ago",
  },
  {
    id: "proj_04",
    name: "Payments Infrastructure",
    description: "Charges, refunds, settlement, and reconciliation services.",
    monitors: 4,
    uptime: 99.94,
    incidents: 0,
    status: "operational" as const,
    owner: "Payments Team",
    lastCheck: "12s ago",
  },
  {
    id: "proj_05",
    name: "Notification Services",
    description: "Email, push, and webhook delivery infrastructure.",
    monitors: 3,
    uptime: 96.21,
    incidents: 1,
    status: "down" as const,
    owner: "Messaging Team",
    lastCheck: "4s ago",
  },
  {
    id: "proj_06",
    name: "Internal Tools",
    description: "Admin dashboards and back-office tooling.",
    monitors: 2,
    uptime: 99.88,
    incidents: 0,
    status: "operational" as const,
    owner: "Tools Team",
    lastCheck: "1m ago",
  },
]

export const incidents = [
  {
    id: "INC-2486",
    title: "Notification worker returning 503s in eu-west-1",
    severity: "critical" as const,
    status: "investigating" as const,
    service: "Notifications Worker",
    affected: ["EU customers", "Webhook subscribers"],
    rootCause: "Downstream queue connection failure",
    startedAt: "14:18 UTC",
    duration: "14m",
    timeline: [
      { time: "14:18", message: "Watcher detected 5 consecutive failed checks" },
      { time: "14:19", message: "Auto-paged on-call engineer (Slack #oncall)" },
      { time: "14:24", message: "Engineer acknowledged, investigating queue" },
    ],
  },
  {
    id: "INC-2485",
    title: "Customer search latency exceeded P95 threshold",
    severity: "high" as const,
    status: "monitoring" as const,
    service: "Customer Search",
    affected: ["Search results", "Customer Portal"],
    rootCause: "Database query plan regression",
    startedAt: "13:42 UTC",
    duration: "50m",
    timeline: [
      { time: "13:42", message: "P95 latency crossed 1000ms threshold" },
      { time: "13:55", message: "Mitigation deployed — index hint applied" },
      { time: "14:30", message: "Latency recovered, monitoring stability" },
    ],
  },
  {
    id: "INC-2484",
    title: "Resolved: Payments API elevated 5xx",
    severity: "medium" as const,
    status: "resolved" as const,
    service: "Payments API",
    affected: ["Checkout API"],
    rootCause: "Bad deployment rolled back",
    startedAt: "May 27, 09:42 UTC",
    duration: "23m",
    timeline: [
      { time: "09:42", message: "Watcher detected 5xx spike" },
      { time: "09:48", message: "Deploy rolled back" },
      { time: "10:05", message: "Incident resolved" },
    ],
  },
  {
    id: "INC-2483",
    title: "Resolved: TLS certificate near expiry",
    severity: "low" as const,
    status: "resolved" as const,
    service: "Public Gateway",
    affected: ["api.acme.com"],
    rootCause: "Cert renewal automation regressed",
    startedAt: "May 25, 22:12 UTC",
    duration: "1h 04m",
    timeline: [
      { time: "22:12", message: "Watcher detected cert expiring in 7 days" },
      { time: "22:18", message: "Engineer rotated cert manually" },
      { time: "23:16", message: "Auto-renewal restored" },
    ],
  },
  {
    id: "INC-2482",
    title: "Resolved: Auth service partial outage",
    severity: "high" as const,
    status: "resolved" as const,
    service: "Auth Service",
    affected: ["Login flows"],
    rootCause: "Upstream identity provider degraded",
    startedAt: "May 24, 03:11 UTC",
    duration: "42m",
    timeline: [
      { time: "03:11", message: "Watcher detected elevated 401s" },
      { time: "03:18", message: "Failover to secondary IdP triggered" },
      { time: "03:53", message: "Service recovered" },
    ],
  },
]

export const regions = [
  { name: "us-east-1", monitors: 9, uptime: 99.97, latency: 142 },
  { name: "us-west-2", monitors: 4, uptime: 99.99, latency: 168 },
  { name: "eu-west-1", monitors: 6, uptime: 96.42, latency: 188 },
  { name: "eu-central-1", monitors: 2, uptime: 99.91, latency: 204 },
  { name: "ap-southeast-1", monitors: 2, uptime: 98.83, latency: 312 },
  { name: "ap-northeast-1", monitors: 1, uptime: 99.94, latency: 288 },
]

export const slowestEndpoints = [
  { name: "Customer Search", url: "/v2/customers/search", p95: 1280, p99: 1842 },
  { name: "Webhooks Dispatcher", url: "/dispatch", p95: 1120, p99: 1612 },
  { name: "Claims Submission", url: "/v1/claims", p95: 522, p99: 712 },
  { name: "Payments API", url: "/v2/charge", p95: 412, p99: 622 },
  { name: "Auth Service", url: "/v2/auth/health", p95: 312, p99: 488 },
]

export const statusPages = [
  {
    id: "sp_01",
    name: "Acme Cloud Status",
    slug: "acme-cloud",
    project: "Core Banking APIs",
    visibility: "public" as const,
    subscribers: 12483,
    uptime: 99.94,
    updatedAt: "2 minutes ago",
  },
  {
    id: "sp_02",
    name: "Acme Customer Portal",
    slug: "customer-portal",
    project: "Customer Portal",
    visibility: "public" as const,
    subscribers: 4218,
    uptime: 99.82,
    updatedAt: "8 minutes ago",
  },
  {
    id: "sp_03",
    name: "Internal Services",
    slug: "internal",
    project: "Internal Tools",
    visibility: "internal" as const,
    subscribers: 142,
    uptime: 99.88,
    updatedAt: "an hour ago",
  },
]

// Time-series data
export const latencyData = Array.from({ length: 24 }).map((_, i) => {
  const base = 140 + Math.sin(i / 3) * 18
  const spike = i === 14 ? 80 : i === 22 ? 40 : 0
  return {
    time: `${String(i).padStart(2, "0")}:00`,
    p50: Math.round(base + spike * 0.4),
    p95: Math.round(base * 2.4 + spike),
    p99: Math.round(base * 4.2 + spike * 1.6),
  }
})

export const uptimeData = Array.from({ length: 30 }).map((_, i) => {
  const dip = i === 12 ? 1.2 : i === 22 ? 2.1 : i === 27 ? 3.6 : 0
  return {
    day: `D${i + 1}`,
    uptime: Math.max(95, +(99.98 - dip + Math.random() * 0.04).toFixed(2)),
  }
})

export const incidentFrequency = Array.from({ length: 6 }).map((_, i) => ({
  week: `W${i + 1}`,
  critical: [0, 1, 0, 0, 1, 1][i],
  high: [1, 0, 2, 1, 1, 1][i],
  medium: [2, 3, 1, 2, 1, 2][i],
  low: [3, 2, 4, 3, 2, 3][i],
}))

export const statusDistribution = [
  { name: "Operational", value: 19, color: "#8fb7ff" },
  { name: "Degraded", value: 3, color: "#f59e0b" },
  { name: "Down", value: 1, color: "#f43f5e" },
  { name: "Paused", value: 1, color: "#94a3b8" },
]

export function sparklineData(base: number) {
  return Array.from({ length: 16 }).map((_, i) => ({
    x: i,
    y: base + Math.sin(i / 2) * 6 + (Math.random() - 0.5) * 4,
  }))
}
